package eu.europa.eudi.elements.android;

import eu.europa.eudi.utils.config.EnvDataConfig;
import io.appium.java_client.AppiumBy;
import org.openqa.selenium.By;

public class WalletElements {

    private static final String APP_PACKAGE = new EnvDataConfig().getAppiumAndroidAppPackage();

    public static final By welcomeScreen = By.id(APP_PACKAGE + ":id/pin_screen_title");
    public static By clickConfirm = By.id(APP_PACKAGE + ":id/pin_screen_button");
    public static By successMessage = By.xpath("//android.widget.TextView[@text=\"Your wallet is secured!\"]");
    public static By clickShare = By.xpath("//android.widget.TextView[@text=\"Share\"]");
    public static By authenticationSuccess = By.xpath("//android.widget.TextView[@text=\"You successfully shared the following information with\"]");
    public static By loginPageIsDisplayed = By.id(APP_PACKAGE + ":id/biometric_screen_title");
    public static By clickPID = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.pid_mdoc,eu.europa.ec.eudi.pid_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt\"]" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.pid_mdoc,eu.europa.ec.eudi.pid_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt\"]/android.view.View" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.pid_mdoc,eu.europa.ec.eudi.pid_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt\"]/android.view.View/android.view.View");
    public static By PIDIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PID\" or @text=\"eu.europa.ec.eudi.pid.1\" or @text=\"PID (MSO MDoc)\"]");
    public static By PIDIsDisplayedPython = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc)\"]");
    public static By clickMdlPython = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.mdl_mdoc\"]" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.mdl_mdoc\"]/android.view.View" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer.eudiw.dev_eu.europa.ec.eudi.mdl_mdoc\"]/android.view.View/android.view.View");
    public static By dashboardPageIsDisplayedSecond = By.xpath("//android.widget.TextView[@text=\"Welcome, Nikos\"]");
    public static By dashboardPageIsDisplayedSecondKotlin = By.xpath("//android.widget.TextView[@text=\"Welcome, Tyler\"]");
    public static By dashboardPageIsDisplayedDeferred = By.xpath("//android.widget.TextView[@text=\"Welcome\"]");
    public static By addDoc = By.xpath("//android.view.View[@content-desc=\"Add\"]");
    public static By addDocumentPageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Add document\"]");
    public static By clickSubmit = By.xpath("//android.widget.Button[@text=\"Submit\"]");
    public static By successMessageForDrivingIsDisplayed = By.xpath("//android.widget.TextView[@text=\"You have successfully added the following to your wallet\"]");
    public static By issuanceDetails = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc)\"]");
    public static By successMessageIsDisplayedForIssuer = By.xpath("//android.widget.TextView[@text=\"You have successfully added the following to your wallet\"]");
    public static By clickExpandVerification = By.xpath("//android.view.View[@content-desc=\"Arrow down\"]");
    public static By pinFieldIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PIN\"]");
    public static By clickAddMyDigitalID = By.id(APP_PACKAGE + ":id/success_screen_primary_button");
    public static By clickDocuments = By.id(APP_PACKAGE + ":id/dashboard_screen_bottom_navigation_item_documents");
    public static By documentsTab = By.xpath("//android.widget.TextView[@text=\"Documents\"]");
    public static By clickClose = By.id(APP_PACKAGE + ":id/document_success_screen_button");
    public static By documentsPageIsDisplayed = By.xpath("(//android.widget.TextView[@text=\"Documents\"])[1]");
    public static By clickToAddDocument = By.id(APP_PACKAGE + ":id/documents_screen_plus_button");
    public static By clickFromList = By.xpath("//android.widget.TextView[@text=\"From list\"]");
    public static By clickBackButton = By.xpath("//android.view.View[@content-desc=\"Go Back\"]");
    public static By secondPidIsDisplayed = By.xpath("(//android.widget.TextView[@text=\"PID (MSO MDoc)\"])");
    public static By homePageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Welcome\"]");
    public static By clickDownArrow = By.xpath("//android.view.View[@content-desc=\"Arrow down\"]");
    public static By clickAdd = By.xpath("//android.widget.TextView[@text=\"Add\"]");
    public static By scanQRButton = By.xpath("//android.view.ViewGroup/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View[2]/android.widget.Button");
    public static By onlyThisTimeQR = By.xpath("//android.widget.Button[@resource-id=\"com.android.permissioncontroller:id/permission_allow_one_time_button\"]");
    public static By authenticateButton = By.xpath("//android.widget.TextView[@text=\"Authenticate\"]");
    public static By walletLink = By.xpath("//android.widget.TextView[@text=\"Link\"]");
    public static By addButton = By.xpath("//android.widget.TextView[@text=\"Accept\"]");
    public static By clickExpandDetails = By.xpath("//android.view.View[@content-desc=\"Arrow down\"]");
    public static By clickPidFromKotlin = By.xpath("//android.widget.TextView[@text=\"PID (MSO MDoc)\"]");;
    public static By clickPidSDJWTFromKotlin = By.xpath("//android.widget.TextView[@text=\"PID (SD-JWT VC Compact)\"]");;
    public static By scanQRIsActivatedForIssuance = By.xpath("//android.widget.TextView[@text=\"Scan a QR code provided from an issuer to add a digital document to your wallet.\"]");
    public static By selectMDLKotlinCredential = By.xpath("//android.widget.CheckBox[@resource-id=\"credentialId-Eaa-0\"]");
    public static By mdlIsDisplayedKotlin = By.xpath("//android.widget.TextView[@text=\"Mobile Driving Licence (MSO MDoc)\"]");
    public static By selectMDLPythonCredential = By.xpath("//android.widget.TextView[@text=\" mDL (MSO Mdoc)\"]/preceding-sibling::android.widget.CheckBox");
    public static By selectPIDPythonCredential = By.xpath("//android.widget.TextView[@text=' PID (MSO Mdoc)']/../android.widget.CheckBox");
    public static By onlinePresentation = By.xpath("//android.widget.TextView[@text=\"Online\"]");
    public static By clickPidFromKotlinFromList = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_eu.europa.ec.eudi.pid_mso_mdoc,eu.europa.ec.eudi.pid_mso_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt,eu.europa.ec.eudi.pid_vc_sd_jwt_deferred\"]" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_eu.europa.ec.eudi.pid_mso_mdoc,eu.europa.ec.eudi.pid_mso_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt,eu.europa.ec.eudi.pid_vc_sd_jwt_deferred\"]/android.view.View" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_eu.europa.ec.eudi.pid_mso_mdoc,eu.europa.ec.eudi.pid_mso_mdoc_deferred,eu.europa.ec.eudi.pid_vc_sd_jwt,eu.europa.ec.eudi.pid_vc_sd_jwt_deferred\"]/android.view.View/android.view.View");
    public static By clickPowerOfPresentation = By.xpath("//android.widget.TextView[@text=\"Power Of Representation (MSO Mdoc)\"]");
    public static By clickMdlKotlin = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_org.iso.18013.5.1.mDL\"]" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_org.iso.18013.5.1.mDL\"]/android.view.View" + " | " + "//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/add_document_screen_attestation_https://issuer-backend.eudiw.dev_org.iso.18013.5.1.mDL\"]/android.view.View/android.view.View");
    public static By selectPIDSDJWTPythonCredential = By.xpath("//android.widget.TextView[@text=\" PID (SD-JWT VC)\"]/preceding-sibling::android.widget.CheckBox");;
    public static By clickPidSDJWTFromKotlinFromList;
    public static By clickExpandVerificationSDJWT = By.xpath("//android.widget.TextView[@text='PID (SD-JWT VC)']");
    public static By pidSdJwtIsDisplayedKotlin = By.xpath("//android.widget.TextView[@text=\"PID (SD-JWT VC Compact)\"]");
    public static By pidSdJwtIsDisplayedOnDocuments = By.xpath("//android.widget.TextView[@text=\"PID (SD-JWT VC)\"]");
    public static By clickPreAuthorizationCode = By.xpath("//android.widget.RadioButton[@resource-id=\"check2\"]");
    public static By deferredIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc Deferred)\" or @text=\"PID (MSO MDoc) (deferred)\"]");
    public static By notificationForDeferred = By.xpath("//android.widget.TextView[@text=\"In progress!\"]");
    public static By pendigStatus = By.xpath("//android.widget.TextView[@text=\"Pending\"]");
    public static By popUpConfirmation = By.xpath("//android.widget.TextView[@text=\"Documents issued\"]");
    public static By pidDefrredIsDisplayedPython = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc Deferred)\"]");
    public static By pidDefrredIsDisplayedKotlin = By.xpath("//android.widget.TextView[@text=\"PID (MSO MDoc) (deferred)\"]");
    public static By clickOkButton = By.xpath("//android.widget.TextView[@text=\"OK\"]");
    public static By inspectDeferredDocument = By.xpath("//android.view.View[@content-desc=\"Arrow right\"]");
    public static By counterIsDisplayed = By.xpath("//android.widget.TextView[@text=\"30/30\"]");
    public static By counterIsDisplayedKotlin = By.xpath("//android.widget.TextView[@text=\"7/7\"]");;
    public static By authenticationError = By.xpath("//android.widget.TextView[@text=\"Invalid pin\"]");
    public static By clickHome = By.xpath("//android.widget.TextView[@text=\"Home\"]");
    public static By pidMdocIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc)\"]");
    public static By eyeIcon = By.xpath("//android.view.View[@content-desc=\"Show\" or @content-desc=\"Hide\"]");
    public static By expiresOnLabel = By.xpath("//android.widget.TextView[starts-with(@text, \"Expires on:\")]");
    public static By issuedOnLabel = By.xpath("//android.widget.TextView[starts-with(@text, \"Issued on:\")]");
    public static By reissueDocumentText = By.xpath("//android.widget.TextView[@text=\"You may reissue this document at any time.\"]");
    public static By threeDotMenu = By.xpath("//android.view.View[@content-desc=\"More Items\"]");
    public static By clickRemoveInDropdown = By.xpath("//android.widget.TextView[@text=\"Remove\"]");
    public static By selectRemove = By.xpath("//android.view.View[contains(@resource-id, \"id/document_details_screen_dialogue_delete_document_positive_button\")]");
    public static By bookmarkIcon = By.xpath("//android.view.View[@content-desc=\"Bookmark\" or @content-desc=\"Bookmark filled\"]");
    public static By closeBookmarkSheet = By.xpath("//android.view.View[contains(@content-desc, \"Close sheet\")]");
    public static By clickSignDocument = By.xpath("//android.widget.TextView[@text=\"Sign\"]");
    public static By clickSelectDocument = By.xpath("//android.widget.TextView[@text=\"Select document\"]");
    public static By selectPDFSample = By.xpath("//android.widget.TextView[@resource-id=\"android:id/title\" and @text=\"sample.pdf\"]");
    public static By clickFromDevice = By.xpath("//android.widget.TextView[@text=\"From device\"]");
    public static By selectSigningService = By.xpath("//android.widget.TextView[@text=\"Select signing service\"]");
    public static By clickProceed = By.xpath("//android.widget.TextView[@text=\"Done\"]");
    public static By selectSigningCertificate = By.xpath("//android.widget.TextView[@text=\"Select signing certificate\"]");
    public static By credentialForTests = By.xpath("//android.widget.TextView[@text=\"This is a credential for tests\"]");
    public static By successfullySigned = By.xpath("//android.widget.TextView[@text=\"You have successfully signed your document.\"]");
    public static By clickX = By.xpath("//android.widget.TextView[@text=\"Close\"]");
    public static By clickContinue = By.xpath("//android.widget.TextView[@text=\"Continue\"]");
    public static By clickView = By.xpath("//android.widget.TextView[@text=\"VIEW\"]");
    public static By trustIconIsDisplayed = By.xpath("//android.widget.ImageView[@content-desc=\"Verified\"]");
    public static By historyIsDisplayed = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/dashboard_screen_bottom_navigation_item_transactions\"]");
    public static By inPersonIsDisplayed = By.xpath("//android.widget.TextView[@text=\"In person\"]");
    public static By onlineIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Online\"]");
    public static By clickScreen = By.xpath("//android.view.ViewGroup/android.view.View/android.view.View/android.view.View/android.view.View[2]");
    public static By signDocument = By.xpath("//android.widget.TextView[@text=\"Sign document\"]");
    public static By homeHighlighted = By.xpath("//android.view.View[@resource-id=\"eu.europa.ec.euidi:id/dashboard_screen_bottom_navigation_item_home\"]");
}
