package eu.europa.eudi.elements.android;

import org.openqa.selenium.By;

public class WalletElements {
    public static final By welcomeScreen = By.xpath("//android.widget.TextView[@resource-id=\"pin_screen_title\"]");
    public static By pinTexfield1 = By.id("pin_text_field_0");
    public static By pinTexfield2 = By.id("pin_text_field_1");
    public static By pinTexfield3 = By.id("pin_text_field_2");
    public static By pinTexfield4 = By.id("pin_text_field_4");
    public static By pinTexfield5 = By.id("pin_text_field_5");
    public static By pinTexfield6 = By.id("pin_text_field_6");
    public static By nextButton = By.id("pin_screen_button");
    public static By clickConfirm = By.id("pin_screen_button]");
    public static By successMessage = By.xpath("//android.widget.TextView[@text=\"Your wallet is secured!\"]");
    public static By clickShare = By.xpath("//android.widget.TextView[@text=\"Share\"]");
    public static By authenticationSuccess = By.xpath("//android.widget.TextView[@text=\"You successfully shared the following information with\"]");
    public static By loginPageIsDisplayed = By.id("biometric_screen_title");
    public static By clickPID = By.id("add_document_screen_attestation_https://ec.dev.issuer.eudiw.dev_eu.europa.ec.eudi.pid_mdoc");
   public static By PIDIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PID\" or @text=\"eu.europa.ec.eudi.pid.1\" or @text=\"PID (MSO Mdoc)\"]");
    public static By clickMdlDemo = By.xpath("//android.widget.TextView[@text=\"mDL (MSO Mdoc)\"]");
    public static By mdlIsDisplayed = By.xpath("//android.widget.TextView[@text=\"mDL (MSO Mdoc)\"]");
    public static By confirmsDeletion = By.id("document_details_screen_dialogue_delete_document_positive_button");
    public static By dashboardPageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Welcome back, Foteini\"]");
    public static By unselectData = By.xpath("//android.widget.TextView[@text=\"Birth Date\"]");
    public static By correspondingMessageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Choosing not to share certain data may result in failure to issue the requested document.\"]");
    public static By addDoc = By.xpath("//android.view.View[@content-desc=\"Add\"]");
    public static By addDocumentPageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Add document\"]");
    public static By clickSubmit = By.xpath("//android.widget.Button[@text=\"Submit\"]");
    public static By successMessageForDrivingIsDisplayed = By.xpath("//android.widget.TextView[@text=\"You have successfully added the following to your wallet\"]");
    public static By issuanceDetails = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc)\"]");
    public static By successMessageIsDisplayedForIssuer = By.xpath("//android.widget.TextView[@text=\"You have successfully added the following to your wallet\"]");

    public static By authorize = By.xpath("//android.widget.Button[@text=\"Authorize\"]");
    public static By detailsOfMdlIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Date of birth\"]");
    public static By detailsOfDocument = By.xpath("//android.widget.TextView[@text=\"Family Name(s)\"]");;
    public static By clickSecondPID = By.xpath("(//android.widget.TextView[@text=\"PID (MSO Mdoc)\"])[2]");
    public static By clickEyeIcon = By.xpath("//android.view.View[@content-desc=\"Hide\"]");
    public static By clickExpandVerification = By.xpath("//android.view.View[@content-desc=\"Arrow down\"]");
    public static By verificationDetails = By.xpath("//android.widget.TextView[@text=\"Birth Date\"]");
    public static By pinFieldIsDisplayed = By.xpath("//android.widget.TextView[@text=\"PIN\"]");
    public static By clickAddMyDigitalID = By.id("success_screen_primary_button");
    public static By clickDocuments = By.id("dashboard_screen_bottom_navigation_item_documents");
    public static By clickClose = By.id("document_success_screen_button");
    public static By documentsPageIsDisplayed = By.xpath("(//android.widget.TextView[@text=\"Documents\"])[1]");
    public static By eyeIcon = By.xpath("//android.view.View[@content-desc=\"Hide\"]"); //androidx.compose.ui.platform.h1/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View/android.view.View[4]/android.widget.Button
    public static By clickToAddDocument = By.id("documents_screen_plus_button");
    public static By clickFromList = By.xpath("//android.widget.TextView[@text=\"From list\"]");
    public static By clickBackButton = By.xpath("//android.view.View[@content-desc=\"Go Back\"]");
    public static By clickHomeButton = By.id("dashboard_screen_bottom_navigation_item_home");
    public static By secondPidIsDisplayed = By.xpath("(//android.widget.TextView[@text=\"PID (MSO Mdoc)\"])[2]");
    public static By clickDeleteDocument = By.id("document_details_screen_delete_button");
    public static By homePageIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Welcome back, Foteini\"]");
    public static By detailsAreBlurred = By.xpath("//android.view.View[@content-desc=\"Hide\"]");
    public static By clickDownArrow = By.xpath("//android.view.View[@content-desc=\"Arrow down\"]");
    public static By closeCorrespondingMessage = By.xpath("//android.view.View[@content-desc=\"Close sheet\"]");
    public static By clickAdd = By.xpath("//android.widget.TextView[@text=\"Add\"]");
    public static By addPIDPageIsDisplayed = By.id("add_document_screen_subtitle");
    public static By successMessageForVerifier = By.xpath("//android.widget.TextView[@text=\"You successfully shared the following information with\"]");
    public static By clickPIDOnDocuments = By.xpath("//android.widget.TextView[@text=\"PID (MSO Mdoc)\"]");
    public static By clickDrivingLicenceButtonOnDocuments = By.xpath("//android.widget.TextView[@text=\"mDL (MSO Mdoc)\"]/ancestor::*[@clickable='true'][1]\n");
    public static By clickPIDOnDocumentsSecond = By.xpath("//android.widget.TextView[@text=\"PID (SD-JWT VC)\"]");
    public static By findConfirm = By.xpath("//android.widget.Button[@text=\"Confirm\"]");
    public static By scanQrIsDisplayed = By.xpath("//android.widget.TextView[@text=\"Scan QR\"]");
    public static By scanQRButton = By.xpath("//android.view.ViewGroup/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View/android.view.View[2]/android.view.View[2]/android.widget.Button");
    public static By onlyThisTimeQR = By.xpath("//android.widget.Button[@resource-id=\"com.android.permissioncontroller:id/permission_allow_one_time_button\"]");
    public static By scanQRIsActivated = By.xpath("//android.widget.TextView[@text=\"Scan a QR code provided from a Relying Party to present a digital document.\"]");
    public static By authenticateButton = By.xpath("//android.widget.TextView[@text=\"Authenticate\"]");
    public static By onlineOption = By.xpath("//android.widget.TextView[@text=\"Online\"]");
    public static By walletLink = By.xpath("//android.widget.TextView[@text=\"Link\"]");
    public static By addButton = By.xpath("//android.widget.TextView[@text=\"Add\"]");
    public static By kotlinIssuanceDetails = By.xpath("//android.widget.TextView[@text=\"PID (MSO MDoc)\"]");
}
