package eu.europa.eudi.elements.conformance;

import org.openqa.selenium.By;

public class ConformanceElements {
    public static final By LOGIN_PAGE_TITLE = By.xpath("//h1[@class='text-center' and contains(text(),'Login to or Register with the OpenID Foundation Conformance Suite')]");
    public static final By BODY_CONTENT = By.xpath("//body");
    public static final By PROCEED_WITH_GOOGLE_BUTTON = By.xpath("//a[@class='btn btn-lg btn-danger bg-gradient border border-secondary' and @href='/oauth2/authorization/google']");
    public static final By EMAIL_INPUT = By.id("identifierId");
    public static final By EMAIL_NEXT_BUTTON = By.id("identifierNext");
    public static final By PASSWORD_INPUT = By.name("Passwd");
    public static final By PASSWORD_NEXT_BTN = By.id("passwordNext");
    public static final By USER_LOGGED_IN = By.xpath("//p[contains(text(), 'Logged in as')]");
    public static final By TEST_PLAN_PAGE = By.xpath("//a[contains(text(), 'OpenID Foundation Certification Instructions')]");
    public static final By SHOW_EARLY_VERSION_TESTS_CHECKBOX = By.id("show-alpha-tests");
    public static final By TEST_PLAN_DROPDOWN = By.id("planSelect");
    public static final By LOADING_MODAL = By.id("loadingModal");
    public static final By SENDER_CONSTRAINING = By.xpath("//label[contains(text(), 'Sender Constraining')]");
    public static final By AUTH_REQUEST_TYPE = By.xpath("//label[contains(text(), 'Authorization Request Type')]");;
    public static final By GRANT_TYPE = By.xpath("//label[contains(text(), 'Grant Type')]");;
    public static final By SENDER_CONSTRAINING_DROPDOWN = By.id("vp_sender_constrain");
    public static final By CLIENT_AUTH_DROPDOWN = By.id("vp_client_auth_type");
    public static final By AUTH_CODE_FLOW_DROPDOWN = By.id("vp_vci_authorization_code_flow_variant");
    public static final By AUTH_REQUEST_DROPDOWN = By.id("vp_authorization_request_type");
    public static final By REQUEST_METHOD_DROPDOWN = By.id("vp_fapi_request_method");
    public static final By GRANT_TYPE_DROPDOWN = By.id("vp_vci_grant_type");
    public static final By METADATA_DISCOVERY_DROPDOWN = By.id("vp_vci_credential_issuer_metadata");
    public static final By FAPI_PROFILE_DROPDOWN = By.id("vp_fapi_profile");
    public static final By FAPI_RESPONSE_DROPDOWN = By.id("vp_fapi_response_mode");
    public static final By CONFIGURE_TEST = By.xpath("//h3[text()='Configure Test']");
    public static final By ALIAS_INPUT = By.cssSelector("input[data-json-target='alias']");
    public static final By PUBLISH_DROPDOWN = By.cssSelector("select[data-json-target='publish']");
    public static final By CREDENTIAL_ISSUER_URL_INPUT = By.cssSelector("input[data-json-target='vci.credential_issuer_url']");
    public static final By CREDENTIAL_CONF_ID_INPUT = By.cssSelector("input[data-json-target='vci.credential_configuration_id']");
    public static final By CREDENTIAL_ISSUER_METADATA_URL_INPUT = By.cssSelector("input[data-json-target='vci.credential_issuer_metadata_url']");
    public static final By AUTH_SERVER_URL_OVERRIDE_INPUT = By.cssSelector("input[data-json-target='vci.authorization_server']");
    public static final By CLIENT_ID_INPUT = By.cssSelector("input[data-json-target='client.client_id']");
    public static final By DPOP_SIGNING_ALG_DROPDOWN = By.cssSelector("select[data-json-target='client.dpop_signing_alg']");
    public static final By EXECUTE_TEST_PLAN_BTN = By.id("createPlanBtn");
    public static final By CREDENTIAL_OFFER_PARAMETER_DROPDOWN = By.id("vp_vci_credential_offer_variant");
    public static final By JWKS_INPUT = By.cssSelector("textarea[data-json-target='client.jwks']");
    public static final By PASSED_TEST = By.xpath("//div[normalize-space(.)='PASSED']");
    public static final By RUN_TEST_BTN = By.cssSelector(".startBtn");
    public static final By TEST_PLAN_RESULTS_PAGE = By.xpath("//div[contains(text(), 'These test results were generated by the OpenID Foundation conformance suite.')]");
}