package eu.europa.eudi.elements.ios;

import org.openqa.selenium.By;

public class IssuerElements {
    public static By requestCredentialsPageIsDisplayed = By.xpath("//XCUIElementTypeOther[@name=\"Request Credentials for your EUDI Wallet\" and @value=\"1\"]");
    public static By clickSubmitButton = By.xpath("//XCUIElementTypeButton[@name=\"Submit\"]");
    public static By qrCodeIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"QR Code\"]");
    public static By qrCodeIsDisplayedKotlin = By.xpath("//XCUIElementTypeStaticText[@name=\"Scan the generated QR Code to issue the requested Credentials:\"]");
    public static By clickEudiwButton = By.xpath("//XCUIElementTypeStaticText[@name=\"Use EUDIW\"]");
    public static By authenticationPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Authentication Method Selection\"]");
    public static By clickCountrySelection = By.xpath("//XCUIElementTypeStaticText[@name=\"Country Selection\"]");
    public static By formIsDisplayed = By.xpath("//*[@label='EUDI Wallet Credential']");
    public static By selectCountryOfOriginIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Please select your country of origin\"]");
    public static By successfullyShared = By.id("document_success_screen_content_header_description");
    public static By authorizePageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Please review the selected attributes before sending to the EudiWallet demo app.\"]");
    public static By clickPID = By.xpath("//XCUIElementTypeStaticText[@label=\"PID (MSO Mdoc)\"]/preceding-sibling::*[1]\n");
    public static By clickCountry = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[13]/XCUIElementTypeTextField[1]");
    public static By clickPlaceOfBirth = By.xpath("//XCUIElementTypeStaticText[@name=\"Place Of Birth\"]");
    public static By clickFormEu = By.xpath("//XCUIElementTypeStaticText[@label=\"FormEU\"]");
    public static By clickGivenName = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[2]");
    public static By givenNameField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[2]");
    public static By clickFamilyName = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By familyNameField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By clickBirthDate = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[7]");
    public static By enterDocumentNumber = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By documentNumberField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By closeKeyboardBefore03 = By.xpath("//XCUIElementTypeStaticText[@name=\"Document Number\"]");
    public static By clickIssueDate = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[10]/XCUIElementTypeOther[6]");
    public static By clickExpiryDate = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[10]/XCUIElementTypeOther[4]");
    public static By clickSubmit = By.xpath("//XCUIElementTypeButton[@name=\"Submit\"]");
    public static By clickScreen = By.xpath("//XCUIElementTypeStaticText[@name=\"Expiry Date\"]");
    public static By authorize = By.xpath("//XCUIElementTypeButton[@name=\"Authorize\"]");
    public static By clickCountryCode = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[11]/XCUIElementTypeTextField");
    public static By closeKeyboard = By.xpath("//XCUIElementTypeStaticText[@name=\"Nationality\"]");
    public static By clickConfirm = By.xpath("//XCUIElementTypeButton[@name=\"Confirm\"]");
    public static By enterCode = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[10]/XCUIElementTypeOther[2]/XCUIElementTypeTextField[1]");
    public static By clickCode = By.xpath("//XCUIElementTypeStaticText[@name=\"Code\"]");
    public static By clickFamilyNameOnMdl = By.xpath("//XCUIElementTypeStaticText[@name='Family Name']/following::XCUIElementTypeTextField[1]");
    public static By clickGivenNameOnMdl = By.xpath("//XCUIElementTypeStaticText[@name='Given Name']/following::XCUIElementTypeTextField[1]");
    public static By clickGivenNameText = By.xpath("//XCUIElementTypeStaticText[@name=\"Given Name\"]");
    public static By pidMsoMdoc = By.xpath("//XCUIElementTypeStaticText[@name=\"eu.europa.ec.eudi.pid_mso_mdoc\"]");
    public static By clickGenerateButton = By.xpath("//XCUIElementTypeButton[@label=\"Generate\"]");
    public static By clickUsername = By.xpath("//XCUIElementTypeTextField");
    public static By clickPassword = By.xpath("//XCUIElementTypeSecureTextField");
    public static By clickSignIn = By.xpath("//XCUIElementTypeButton[@name=\"Sign In\"]");
    public static By issueCredentialPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Scan the generated QR Code to issue the requested Credentials:\"]");
    public static By signPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Sign in to your account\"]");
    public static By nationality = By.xpath("//XCUIElementTypeStaticText[@name=\"Nationality\"]");
}