package eu.europa.eudi.elements.ios;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class WalletElements {
    public static final By welcomeScreen = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome to your wallet\"]");
    public static By welcomePage = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome to your wallet\"]");
    public static By pinTexfield1 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[1]");
    public static By pinTexfield2 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[2]");
    public static By pinTexfield3 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[3]");
    public static By pinTexfield4 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[4]");
    public static By pinTexfield5 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[5]");
    public static By pinTexfield6 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[5]");
    public static By nextButton = By.xpath("//XCUIElementTypeButton[@name=\"Proceed\"]");
    public static By clickConfirm = By.xpath("//XCUIElementTypeButton[@name=\"Confirm\"]");
    public static By successMessage = By.xpath("//XCUIElementTypeStaticText[@name=\"Your wallet is secured!\"]");
    public static By clickContinue = By.xpath("//XCUIElementTypeButton[@name=\"CONTINUE\"]");
    public static By chooseSampleData = By.xpath("//XCUIElementTypeStaticText[@name=\"Load Sample Data\"]");
    public static By dashboardPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome back, Foteini\"]");
    public static By appOpensSuccessfully = By.xpath("//XCUIElementTypeButton[@name=\"PID authentication\"]");
    public static By clickShareData = By.xpath("//XCUIElementTypeStaticText[@label=\"Request to share specific attributes from PID\"]");
    public static By clickNext = By.xpath("//XCUIElementTypeButton[@name=\"NEXT\"]");
    public static By chooseData = By.xpath("//XCUIElementTypeSwitch[@name=\"Family name\"]");
    public static By authenticationPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Proceed to authentication\"]");
    public static By chooseWallet = By.xpath("//XCUIElementTypeStaticText[@name=\"AUTHENTICATE WITH WALLET\"]");
    public static By viewDataPage = By.xpath("//XCUIElementTypeStaticText[@name=\"Please review carefully before sharing your data. Why we need your data?\"]");
    public static By clickShare = By.xpath("//XCUIElementTypeButton[@name=\"SHARE\"]");
    public static By authenticationSuccess = By.xpath("//XCUIElementTypeStaticText[@name=\"You successfully shared information with EUDI Remote Verifier\"]");
    public static By clickNationalId = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By nationalIdIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"PID\"]");
    public static By clickMdl = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving License\"]");
    public static By mdlIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving License\"]");
    public static By addDoc = By.xpath("//XCUIElementTypeStaticText[@name=\"ADD DOC\"]");
    public static By addDocumentPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Add document\"]");
    public static By clickNationalIdButton = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By authenticationMethodSelection = By.xpath("//XCUIElementTypeStaticText[@name=\"Authentication Method Selection\"]");
    public static By clickSubmit = By.xpath("//XCUIElementTypeButton[@name=\"Submit\"]");
    public static By clickFormEu = By.xpath("//XCUIElementTypeStaticText[@name=\"FormEU\"]");
    public static By dataPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Enter the data for your EUDI Wallet\"]");
    public static By clickGivenName = By.xpath("//XCUIElementTypeTextField[@name=\"Given Name\"]");
    public static By givenNameField = By.xpath("//XCUIElementTypeTextField[@name=\"Given Name\"]");
    public static By clickFamilyName = By.xpath("//XCUIElementTypeTextField[@name=\"Family Name\"]");
    public static By givenFamilyField = By.xpath("//XCUIElementTypeTextField[@name=\"Family Name\"]");
    public static By clickBirthDate = By.xpath("//XCUIElementTypeOther[@name=\"Birth Date\"]");
    public static By chooseSet = By.xpath("//XCUIElementTypeButton[@name=\"Done\"]");
    public static By successMessageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"You can now add your National ID\"]");
    public static By clickDeleteButton = By.xpath("//XCUIElementTypeButton[@name=\"Bin\"]");
    public static By confirmsDeletion = By.xpath("//XCUIElementTypeButton[@name=\"yes\"]");
    public static By loginPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Login\"]");
    public static By enterDocumentNumber = By.xpath("//XCUIElementTypeTextField[@name=\"document_number\"]");
    public static By documentNumberField = By.xpath("//XCUIElementTypeTextField[@name=\"document_number\"]");
    public static By clickScreen = By.xpath("//XCUIElementTypeStaticText[@name=\"Portrait:\"]");
    public static By clickIssueDate = By.xpath("//XCUIElementTypeOther[@name=\"Issue Date\"]");
    public static By clickExpiryDate = By.xpath("//XCUIElementTypeOther[@name=\"Expiry Date\"]");
    public static By successMessageForDrivingIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"You can now add your Driving License\"]");
    public static By drivingLicenceIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving License\"]");
    public static By clickXButton = By.xpath("//XCUIElementTypeButton[@name=\"Close\"]");
    public static By drivingLicenceIsDisplayedInDashboard = By.xpath("(//XCUIElementTypeStaticText[@name=\"Driving License\"])[2]");
    public static By clickDrivingLicenceButton = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving License\"]");
    public static By unselectData = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By correspondingMessageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Your selection of data to be shared may impact the service\"]");
    public static By clickaAgainData = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By issuanceDetails = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By clickIssue = By.xpath("//XCUIElementTypeButton[@name=\"ISSUE\"]");
    public static By successMessageIsDisplayedForIssuer = By.xpath("//XCUIElementTypeStaticText[@name=\"Your documents from issuer.eudiw.dev have been successfully issued.\"]");
    public static By detailsOfNationalIdIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By detailsOfMdlIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By chooseData2 = By.xpath("//XCUIElementTypeSwitch[@name=\"Given name\"]");
    public static By optionalDataIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By clickEyeIcon = By.xpath("//XCUIElementTypeImage[@name=\"Show\"]");
    public static By actuallDataIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"ANDERSSON\"]");
    public static By authorize = By.xpath("//XCUIElementTypeButton[@name=\"Authorize\"]");
    public static By pinFieldIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"EUDI Remote Verifier requests the following\"]");
    public static By detailsOfDocument = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By clickSecondNationalId = By.xpath("(//XCUIElementTypeStaticText[@name=\"National ID\"])[2]");
    public static By clickExpandVerification = By.xpath("//XCUIElementTypeStaticText[@name=\"Verification Data\"]");
    public static By verificationDetails = By.xpath("//XCUIElementTypeStaticText[@name=\"Date of issuance\"]");
    public static By clickAddMyDigitalID = By.xpath("//XCUIElementTypeButton[@name=\"Add my Digital ID\"]");
    public static By clickPID = By.xpath("//XCUIElementTypeStaticText[@name=\"PID\"]");
    public static By clickBirthPlace = By.xpath("//XCUIElementTypeTextField[@name=\"Birth Place\"]");
    public static By clickCountryCode = By.xpath("//XCUIElementTypeTextField[@name=\"Country Code\"]");
    public static By clickDone = By.xpath("//XCUIElementTypeButton[@name=\"Done\"]");
    public static By clickOnDocuments = By.xpath("//XCUIElementTypeButton[@name=\"doc.fill\"]");
}
