package eu.europa.eudi.elements.ios;

import io.appium.java_client.AppiumBy;
import org.openqa.selenium.By;

public class WalletElements {
    public static final By welcomeScreen = By.id("pin_screen_title");
    public static By pinTexfield1 = By.id("pin_text_field_0");
    public static By pinTexfield2 = By.id("pin_text_field_1");
    public static By pinTexfield3 = By.id("pin_text_field_2");
    public static By pinTexfield4 = By.id("pin_text_field_3");
    public static By pinTexfield5 = By.id("pin_text_field_4");
    public static By pinTexfield6 = By.id("pin_text_field_5");
    public static By successMessage = By.id("success_screen_title");
    public static By dashboardPageIsDisplayed = By.id("home_tab_screen_username_text");
    public static By clickShare = By.id("request_screen_share_button");
    public static By authenticationSuccess = By.xpath("//XCUIElementTypeStaticText[@label=\"You successfully shared the following information with\"]");
    public static By clickMdl = By.id("mDL (MSO Mdoc)");
    public static By addDoc = By.xpath("//XCUIElementTypeStaticText[@label=\"ADD DOC\"]");
    public static By addDocumentPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@label=\"Add document\"]");
    public static By clickSubmit = By.xpath("//XCUIElementTypeButton[@label=\"Submit\"]");
    public static By loginPageIsDisplayed = By.id("biometric_screen_pin_title");
    public static By successMessageForDrivingIsDisplayed = By.id("document_success_screen_content_header_description");
    public static By clickIssue = By.id("document_offer_screen_issue_button");
    public static By successMessageIsDisplayedForIssuer = By.id("document_success_screen_content_header_description");
    public static By pinFieldIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@label=\"Enter your PIN\"]");
    public static By clickExpandVerification = By.xpath("//XCUIElementTypeImage[@label=\"Go Down\"]");
    public static By clickExpandVerificationForSDJWT = By.xpath("//XCUIElementTypeStaticText[contains(@name, \"PID (SD-JWT VC\")]");
    public static By clickExpandVerificationMSODoc = By.xpath("//XCUIElementTypeStaticText[@name=\"PID (MSO Mdoc)\"]");
    public static By clickExpandNationality = By.xpath("//XCUIElementTypeStaticText[@label='Nationality' or @name='Nationalities']");
    public static By clickExpandPlaceOfBirth = By.xpath("//XCUIElementTypeButton[.//XCUIElementTypeStaticText[@label='Place of Birth' or @name='Birth Place']]");
    public static By clickAddMyDigitalID = By.id("Go to home");
    public static By clickPID = By.id("PID Combined");
    public static By clickDone = By.id("document_success_screen_done_button");
    public static By clickOnDocuments = By.id("documents_tab");
    public static By homePageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome back, Foteini\"]");
    public static By documentsPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Documents\"]");
    public static By PIDIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"PID\" or @name=\"eu_pid_doctype_name\" or @name=\"PID (MSO Mdoc)\"]");
    public static By clickBackButton = By.xpath("//XCUIElementTypeButton[@label=\"Back\"] | //XCUIElementTypeButton[@name=\"chevron.left\"]");
    public static By clickToAddDocument = By.id("plus");
    public static By clickFromList = By.id("Choose from list");
    public static By secondPidIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@label='PID (MSO Mdoc)'] | //XCUIElementTypeStaticText[@name='PID (MSO Mdoc)'] | //XCUIElementTypeStaticText[@name='PID (MSO MDoc)']");
    public static By pinTexfield1Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[1]");
    public static By pinTexfield2Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[2]");
    public static By pinTexfield3Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[3]");
    public static By pinTexfield4Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[4]");
    public static By pinTexfield5Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[5]");
    public static By pinTexfield6Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[6]");
    public static By clickDownArrow = By.xpath("//XCUIElementTypeImage[@label=\"Go Down\"]");
    public static By issuanceDetailsNew = By.xpath("//XCUIElementTypeStaticText[@name=\"PID (MSO Mdoc)\"]");
    public static By authenticateButton = By.xpath("//XCUIElementTypeButton[@label=\"Authenticate\"]");
    public static By scanQRIsActivated = By.xpath("//XCUIElementTypeStaticText[@label=\"Scan a QR code provided from an issuer to add a digital document to your wallet.\"]");
    public static By walletLink = By.xpath("//XCUIElementTypeStaticText[@name=\"Link\"]");
    public static By selectMDLKotlin = AppiumBy.iOSNsPredicateString("type == 'XCUIElementTypeStaticText' AND name == 'org.iso.18013.5.1.mDL'");
    public static By selectMDLPython = By.xpath("//XCUIElementTypeStaticText[@name='mDL (MSO Mdoc)']/preceding-sibling::XCUIElementTypeSwitch[1]");
    public static By selectPIDPython = By.xpath("//XCUIElementTypeStaticText[@name='PID (MSO Mdoc)']/preceding-sibling::XCUIElementTypeSwitch[1]");
    public static By selectPIDSDJWTPython = By.xpath("//XCUIElementTypeStaticText[@name='PID (SD-JWT VC)']/preceding-sibling::XCUIElementTypeSwitch[1]");
    public static By mdlIsDisplayedKotlin = By.xpath("(//XCUIElementTypeStaticText[@name=\"Mobile Driving Licence (MSO MDoc)\"])");
    public static By clickPidFromKotlin = By.xpath("//XCUIElementTypeStaticText[@name=\"PID (MSO MDoc)\"]");
    public static By scanQR = By.id("Scan QR");
    public static By clickMdlKotlin = By.id("Mobile Driving Licence (MSO MDoc)");
    public static By pidMdocIsDisplayed = AppiumBy.accessibilityId("PID (MSO Mdoc)");
    public static By pidSdJwtIsDisplayedOnDocuments = AppiumBy.accessibilityId("PID (SD-JWT VC Compact)");
    public static By pidSdJwtIsDisplayedOnDocumentsPython = AppiumBy.accessibilityId("PID (SD-JWT VC)");
    public static By clickPidSdjwt =  By.id("PID (SD-JWT VC)");
    public static By clickExpandDetails = By.xpath("//XCUIElementTypeImage[@label=\"Go Down\"]");
    public static By clickPreAuthorizationCode = By.xpath("//XCUIElementTypeOther[@name=\"Pre-Authorization Code Grant\"]");
    public static By clickOkButton = By.xpath("//android.widget.TextView[@text=\"OK\"]");
    public static By inspectDeferredDocument = By.xpath("//android.view.View[@content-desc=\"Arrow right\"]");
    public static By clickHome = By.xpath("//XCUIElementTypeButton[@name=\"home_tab\"]");
    public static By clickSignDocument = By.xpath("//XCUIElementTypeButton[@name=\"home_tab_screen_dialog_sign_button\"]");
    public static By clickSelectDocument = By.xpath("//XCUIElementTypeStaticText[@name=\"Select document\"]");
    public static By selectPDFSample = By.xpath("//XCUIElementTypeCell[@name=\"sample, pdf\"]/XCUIElementTypeOther[2]");
    public static By selectSigningService = By.xpath("//XCUIElementTypeStaticText[@name=\"Select signing service\"]");
    public static By clickWalletCentric = By.xpath("//XCUIElementTypeStaticText[@name=\"Wallet-Centric\"]");
    public static By clickProceed = By.xpath("//XCUIElementTypeButton[@name=\"Proceed\"]");
    public static By selectSigningCertificate = By.xpath("//XCUIElementTypeStaticText[@name=\"Select signing certificate\"]");
    public static By credentialForTests = By.xpath("//XCUIElementTypeStaticText[@name=\"This is a credential for tests\"]");
    public static By successfullySigned = By.xpath("//XCUIElementTypeStaticText[@name=\"You have successfully signed your document.\"]");
    public static By clickX = By.xpath("//XCUIElementTypeButton[@name=\"xmark\"]");
    public static By placeOfBirth = By.xpath("//XCUIElementTypeStaticText[@name=\"Birth Place\"]");
    public static By eyeIcon = By.xpath("//XCUIElementTypeButton[@name=\"document_details_screen_eye_slash_button\" or @name=\"document_details_screen_eye_button\"]");
    public static By bookmarkIcon = By.xpath("//XCUIElementTypeButton[@name=\"bookmark\" or @name=\"bookmark.fill\"]");
    public static By deferredPid = By.xpath("//XCUIElementTypeStaticText[@name=\"PID (MSO Mdoc Deferred)\"]");
}