package eu.europa.eudi.elements.ios;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class WalletElements {
    public static final By welcomeScreen = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome to your wallet\"]");
    public static By welcomePage = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome to your wallet\"]");
    public static By pinTexfield1 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[1]");
    public static By pinTexfield2 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[2]");
    public static By pinTexfield3 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[3]");
    public static By pinTexfield4 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[4]");
    public static By pinTexfield5 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[5]");
    public static By pinTexfield6 = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[6]");
    public static By nextButton = By.xpath("//XCUIElementTypeButton[@name=\"Proceed\"]");
    public static By clickConfirm = By.xpath("//XCUIElementTypeButton[@name=\"Confirm\"]");
    public static By successMessage = By.xpath("//XCUIElementTypeStaticText[@name=\"Your wallet is secured!\"]");
    public static By clickContinue = By.xpath("//XCUIElementTypeButton[@name=\"CONTINUE\"]");
    public static By chooseSampleData = By.xpath("//XCUIElementTypeStaticText[@name=\"Load Sample Data\"]");
    public static By dashboardPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome back, Foteini\"]");
    public static By appOpensSuccessfully = By.xpath("//XCUIElementTypeStaticText[@name=\"Define your presentation request\"]");
    public static By clickShareData = By.xpath("//XCUIElementTypeStaticText[@label=\"Request to share specific attributes from PID\"]");
    public static By clickNext = By.xpath("//XCUIElementTypeButton[@name=\"NEXT\"]");
    public static By chooseData = By.xpath("//XCUIElementTypeSwitch[@name=\"Family name\"]");
    public static By authenticationPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Proceed to authentication\"]");
    public static By chooseWallet = By.xpath("//XCUIElementTypeStaticText[@name=\"OPEN WITH YOUR WALLET\"]");
    public static By viewDataPage = By.xpath("//XCUIElementTypeStaticText[@name=\"The following transaction requires your permission and authentication.\"]");
    public static By clickShare = By.xpath("//XCUIElementTypeButton[@name=\"Share\"]");
    public static By authenticationSuccess = By.xpath("//XCUIElementTypeStaticText[@name=\"You successfully shared the following information with\"]");
    public static By clickNationalId = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By nationalIdIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"PID\"]");
    public static By clickMdl = By.xpath("//XCUIElementTypeStaticText[contains(@name, \"mDL\") or contains(@name, \"eu.europa.ec.eudi.mdl_mdoc\")]");
    public static By mdlIsDisplayed = By.xpath("//XCUIElementTypeStaticText[contains(@name, \"mDL\") or contains(@name, \"mdl_doctype_name\")]");
    public static By addDoc = By.xpath("//XCUIElementTypeStaticText[@name=\"ADD DOC\"]");
    public static By addDocumentPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Add document\"]");
    public static By clickNationalIdButton = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By authenticationMethodSelection = By.xpath("//XCUIElementTypeStaticText[@name=\"Authentication Method Selection\"]");
    public static By clickSubmit = By.xpath("//XCUIElementTypeButton[@name=\"Submit\"]");
    public static By clickFormEu = By.xpath("//XCUIElementTypeStaticText[@name=\"FormEU\"]");
    public static By dataPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Enter the data for your EUDI Wallet\"]");
    public static By clickGivenName = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[2]");
    public static By givenNameField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[2]");
    public static By clickFamilyName = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By givenFamilyField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[1]");
    public static By clickBirthDate = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeOther[9]");
    public static By chooseSet = By.xpath("//XCUIElementTypeButton[@name=\"Done\"]");
    public static By successMessageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"You can now add your National ID\"]");
    public static By clickDeleteButton = By.xpath("//XCUIElementTypeButton[@name=\"Bin\"]");
    public static By confirmsDeletion = By.xpath("//XCUIElementTypeButton[@name=\"Delete document\"]");
    public static By loginPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Login\"]");
    public static By enterDocumentNumber = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[3]");
    public static By documentNumberField = By.xpath("//XCUIElementTypeOther[@name=\"main\"]/XCUIElementTypeTextField[3]");
    public static By clickScreen = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving Privileges\"]");
    public static By clickIssueDate = By.xpath("//XCUIElementTypeOther[@name=\"Vehicle Category Code Issue Date Expiry Date Codes Code Sign Value\"]/XCUIElementTypeOther[3]");
    public static By clickExpiryDate = By.xpath("//XCUIElementTypeOther[@name=\"Vehicle Category Code Issue Date Expiry Date Codes Code Sign Value\"]/XCUIElementTypeOther[5]");
    public static By successMessageForDrivingIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"You successfully shared the following information with\"]");
    public static By drivingLicenceIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Driving License\"]");
    public static By clickXButton = By.xpath("//XCUIElementTypeButton[@name=\"Close\"]");
    public static By drivingLicenceIsDisplayedInDashboard = By.xpath("(//XCUIElementTypeStaticText[@name=\"Driving License\"])[2]");
    public static By clickDrivingLicenceButton = By.xpath("//XCUIElementTypeStaticText[@name=\"mDL\"]");
    public static By unselectData = By.xpath("(//XCUIElementTypeButton[@name=\"checkmark.square.fill\"])[1]");
    public static By correspondingMessageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Your selection of data to be shared may impact the service\"]");
    public static By clickaAgainData = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By issuanceDetails = By.xpath("//XCUIElementTypeStaticText[@name=\"National ID\"]");
    public static By clickIssue = By.xpath("//XCUIElementTypeButton[@name=\"Issue\"]");
    public static By successMessageIsDisplayedForIssuer = By.xpath("//XCUIElementTypeStaticText[@name=\"You successfully shared the following information with\"]");
    public static By detailsOfNationalIdIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By detailsOfMdlIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family name\"]");
    public static By chooseData2 = By.xpath("//XCUIElementTypeSwitch[@name=\"Given name\"]");
    public static By optionalDataIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name\"]");
    public static By clickEyeIcon = By.xpath("//XCUIElementTypeButton[@name=\"eye.slash\"]");
    public static By actuallDataIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"ANDERSSON\"]");
    public static By authorize = By.xpath("//XCUIElementTypeButton[@name=\"Authorize\"]");
    public static By pinFieldIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Enter your PIN to share data\"]");
    public static By detailsOfDocument = By.xpath("//XCUIElementTypeStaticText[@name=\"Family Name(s)\"]");
    public static By clickSecondNationalId = By.xpath("(//XCUIElementTypeStaticText[@name=\"National ID\"])[2]");
    public static By clickExpandVerification = By.xpath("//XCUIElementTypeImage[@name=\"chevron.down\"]");
    public static By verificationDetails = By.xpath("//XCUIElementTypeStaticText[@name=\"Birth Date\"]");
    public static By clickAddMyDigitalID = By.xpath("//XCUIElementTypeButton[@name=\"Add my Digital ID\"]");
    public static By clickPID = By.xpath("//XCUIElementTypeStaticText[contains(@name, \"PID\") or contains(@name, \"eu.europa.ec.eudi.pid_mdoc\")]");
    public static By clickBirthPlace = By.xpath("//XCUIElementTypeTextField[@name=\"Birth Place\"]");
    public static By clickCountryCode = By.xpath("(//XCUIElementTypeOther[@name=\"Country Code\"])[1]/XCUIElementTypeTextField");
    public static By clickDone = By.xpath("//XCUIElementTypeButton[@name=\"Done\"]");
    public static By clickOnDocuments = By.xpath("//XCUIElementTypeButton[@name=\"doc.fill\"]");
    public static By homePageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Welcome back, Foteini\"]");
    public static By documentsPageIsDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Documents\"]");
    public static By PIDIsDisplayed = By.xpath("//XCUIElementTypeStaticText[contains(@name, \"PID\") or contains(@name, \"eu_pid_doctype_name\")]");
    public static By detailsAreBlurred = By.xpath("//XCUIElementTypeButton[@name=\"eye.slash\"]");
    public static By eyeIcon = By.xpath("//XCUIElementTypeButton[@name=\"eye.slash\"]");
    public static By detailsAreNotBlurred = By.xpath("//XCUIElementTypeButton[@name=\"eye\"]");
    public static By clickBackButton = By.xpath("//XCUIElementTypeButton[@name=\"chevron.left\"]");
    public static By clickHomeButton = By.xpath("//XCUIElementTypeButton[@name=\"house.fill\"]");
    public static By clickToAddDocument = By.xpath("//XCUIElementTypeOther[@name=\"plus\"]");
    public static By clickFromList = By.xpath("//XCUIElementTypeStaticText[@name=\"Choose from list\"]");
    public static By credentialsProviderDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Test Credentials Provider\"]");
    public static By secondPidIsDisplayed = By.xpath("(//XCUIElementTypeStaticText[@name=\"PID\"])[2]");
    public static By clickSecondPID = By.xpath("(//XCUIElementTypeStaticText[@name=\"PID\"])[2]");
    public static By clickDeleteDocument = By.xpath("//XCUIElementTypeButton[@name=\"Delete document\"]");
    public static By clickaAttributesBy = By.xpath("(//XCUIElementTypeButton[@name=\"-- attributes by --\"])[3]");
    public static By clickPersonIdentificationData = By.xpath("//XCUIElementTypeButton[@name='Person Identification Data (PID)']");
    public static By closeKeyboard = By.xpath("//XCUIElementTypeStaticText[@name=\"Nationality\"]");
    public static By pinTexfield1Ver = By.xpath("//XCUIElementTypeKey[@name=\"1\"]");
    public static By pinTexfield2Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[3]");
    public static By pinTexfield3Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[4]");
    public static By pinTexfield4Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[5]");
    public static By pinTexfield5Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[6]");
    public static By pinTexfield6Ver = By.xpath("//XCUIElementTypeApplication[@name=\"EUDI Wallet\"]/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeImage[7]");
    public static By clickDownArrow = By.xpath("//XCUIElementTypeImage[@name=\"chevron.down\"]");
    public static By walletResponded = By.xpath("//XCUIElementTypeStaticText[@name=\"eu.europa.ec.eudi.pid.1\"]");
    public static By issuanceDetailsNew = By.xpath("//XCUIElementTypeStaticText[@name=\"PID\"]");
    public static By clickAdd = By.xpath("//XCUIElementTypeStaticText[@name=\"Add\"]");
    public static By chooseWalletPageDisplayed = By.xpath("//XCUIElementTypeStaticText[@name=\"Invoke Wallet\"]");
    public static By clickTransactionsLogs = By.xpath("//XCUIElementTypeStaticText[@name=\"transaction log\"]");
    public static By clickTransactionInitialized = By.xpath("XCUIElementTypeButton[1]");
    public static By vehicleCategoryCode = By.xpath("//XCUIElementTypeOther[@name=\"Vehicle Category Code Issue Date Expiry Date Codes Code Sign Value\"]/XCUIElementTypeTextField");
    public static By clickAddOptionalAttributes = By.xpath("//XCUIElementTypeButton[@name=\"Add Optional Attributes\"]");
    public static By clickAgeOver18OnIssuer = By.xpath("//XCUIElementTypeStaticText[@name=\"Age Over 18\"]");
    public static By clickAddAttributes = By.xpath("//XCUIElementTypeButton[@name=\"Add Attributes\"]");
    public static By enableAgeOver18 = By.xpath("//XCUIElementTypeSwitch[@value=\"0\"]");
    public static By clickConfirmOnIssuer = By.xpath("//XCUIElementTypeButton[@name=\"Confirm\"]");
    public static By clickAddDocument = By.xpath("//XCUIElementTypeOther[@name=\"plus\"]");
    public static By closeKeyboardBefore03 = By.xpath("//XCUIElementTypeStaticText[@name=\"Portrait\"]");
    public static By codeFieldIssuer = By.xpath("//XCUIElementTypeOther[@name=\"Code Sign Value\"]/XCUIElementTypeTextField[1]");
    public static By signFieldIssuer = By.xpath("//XCUIElementTypeOther[@name=\"Code Sign Value\"]/XCUIElementTypeTextField[2]");
    public static By valueFieldIssuer = By.xpath("//XCUIElementTypeOther[@name=\"Code Sign Value\"]/XCUIElementTypeTextField[3]");
}