name: Android Automation Tests Execution

on:
  workflow_dispatch:
    inputs:
      branch-to-checkout:
        description: 'Branch to checkout'
        type: choice
        options:
          - main
          - develop
          - milestone/2025.Q4
          - milestone/2026.Q1
        default: develop

      test-cases:
        description: 'Choose Test Cases'
        type: string
        default: "@automated"

      platform:
        description: 'Platform to test - android'
        type: choice
        options:
          - ANDROID
        default: ANDROID

  # schedule:
  #   # WED,SAT 03:15 UTC
  #   - cron: '15 3 * * 3,6'

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 240 # increase IF needed
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v5 # Checkout the code
        with:
          fetch-depth: 0
          clean: true
          lfs: false
          ref: ${{ inputs.branch-to-checkout }}

      - name: Download Latest Release APK
        env:
          REPO: eu-digital-identity-wallet/eudi-app-android-wallet-ui
        run: |
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          latest_release=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO/releases/latest")
          echo "Latest Release JSON: $latest_release"
          apk_url=$(echo "$latest_release" | jq -r '.assets[] | select(.name | contains("Demo.apk")) | .browser_download_url')
          if [ -z "$apk_url" ]; then
            echo "No APK found in the latest release."
            exit 1
          fi
          echo "Downloading APK from: $apk_url"
          curl -L -o app.apk "$apk_url"

      - name: Verify APK file
        run: |
          ls -lh app.apk
          file app.apk
          zipinfo -1 app.apk | head -n 10

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Set up Node JS
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Clean Old Results
        run: |
          rm -rf target/serenity
          rm -rf target/site/reports
          rm -rf target/site/serenity

      - name: Initialize Session Map
        run: echo "" > session_map.txt

      - name: Check jq Installation
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq not found, installing..."
            brew install jq
          else
            echo "jq is already installed."
            jq --version
          fi

      - name: Check BrowserStack Credentials
        run: |
          response=$(curl -u "${BROWSERSTACK_USERNAME}:${BROWSERSTACK_ACCESS_KEY}" https://api.browserstack.com/automate/plan.json)
          echo "BrowserStack Response: $response"

      - name: Upload app to BrowserStack
        id: upload_app
        run: |
          response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@app.apk")
          echo "Response: $response"
          app_url=$(echo $response | jq -r '.app_url')
          echo "app_url=$app_url" >> $GITHUB_OUTPUT

      - name: Get Latest BrowserStack Build ID
        id: fetch-build
        if: always()
        run: |
          BUILD_ID=$(curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" \
            -X GET "https://api-cloud.browserstack.com/app-automate/builds.json" \
            | jq -r '.[0].automation_build.hashed_id')
          echo "BUILD_ID=$BUILD_ID"
          echo "buildid=$BUILD_ID" >> $GITHUB_OUTPUT

      # ---------------- RUN TESTS ----------------
      - name: Run Android Tests on BrowserStack
        env:
          TEST_CASES: ${{ inputs.test-cases }}
        if: ${{ inputs.platform == 'ANDROID' }}
        continue-on-error: true
        run: |
          TEST_TAGS="$TEST_CASES and @ANDROID"
          echo "Running tests: $TEST_TAGS"

          mvn test -ntp \
            -Dcucumber.filter.tags="$TEST_TAGS"

      # ---------------- BACKUP RESULTS ----------------
      - name: Backup Serenity JSON Results
        if: always()
        run: |
          mkdir -p target/serenity-backup
          cp target/site/reports/EUDI_Wallet_Version_2025.12.34-Demo/*.json target/serenity-backup/ || true

      # ---------------- RERUN PASS 1 ----------------
      - name: Rerun Pass 1
        if: always()
        run: |
          if [ -s target/rerun.txt ]; then
            echo "Running rerun pass 1..."
            mvn test -Dtest=RerunTestRunner
          else
            echo "No rerun.txt found"
          fi

      - name: Merge Results Pass 1
        if: always()
        run: |
          python3 merge_serenity_results.py || true

      # ---------------- RERUN PASS 2 ----------------
      - name: Rerun Pass 2
        if: always()
        run: |
          if [ -s target/rerun2.txt ]; then
            echo "Running rerun pass 2..."
            mvn test -Dtest=RerunTestRunner -Dcucumber.features="@target/rerun2.txt"
          else
            echo "No rerun2.txt found"
          fi

      - name: Final Merge Results
        if: always()
        run: |
          python3 merge_serenity_results.py || true

      # ---------------- REPORT ----------------
      - name: Generate Serenity Report
        if: always()
        run: |
          mvn serenity:aggregate -Dtags="${{ inputs.test-cases }} and (@ANDROID or @IOS)"

      - name: Replace Serenity Core CSS
        if: always()
        run: |
          REPORT_DIR="target/site/reports/EUDI_Wallet_Version_2025.12.34-Demo"
          cp src/test/resources/custom-style.css "$REPORT_DIR/css/core.css" || true

      # ---------------- ARTIFACTS ----------------
      - name: Upload Serenity Report
        uses: actions/upload-artifact@v5

        if: always()
        with:
          name: android-serenity-report
          path: target/site/

      - name: Download BrowserStack Device Logs per Feature (Android)
        if: always() && (inputs.platform == 'ANDROID' || inputs.platform == 'both')
        run: | 
         BUILD_ID="${{ steps.fetch-build.outputs.buildid }}" 
         mkdir -p android-logs 
         while IFS='=' read FEATURE SESSION_ID; do 
         [[ "$FEATURE" != *"_Android" ]] && continue 
         FEATURE_CLEAN=$(echo "$FEATURE" | tr -d '[:space:]') 
         echo "Downloading logs for Android: $FEATURE_CLEAN | Session: $SESSION_ID" 
         curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESS_KEY }}" \ 
         -X GET "https://api-cloud.browserstack.com/app-automate/builds/$BUILD_ID/sessions/$SESSION_ID/devicelogs" \ 
         -o "android-logs/${FEATURE_CLEAN}.txt" 
         done < session_map.txt #

      - name: Upload Android Logs
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: android-device-logs
          path: android-logs/

      - name: Upload Serenity JSON Results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: android-serenity-json
          path: target/site/reports/EUDI_Wallet_Version_2025.12.34-Demo/*.json